package com.soundcloud.android;

/* renamed from: com.soundcloud.android.h reason: case insensitive filesystem */
/* compiled from: Actions */
public final class C2929h {
    public static final String a;
    public static final String b;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(C5292SGa.a());
        sb.append(".action.RECORD");
        a = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(C5292SGa.a());
        sb2.append(".action.RECORD_START");
        b = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append(C5292SGa.a());
        sb3.append(".action.RECORD_STOP");
        c = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append(C5292SGa.a());
        sb4.append(".action.STREAM");
        d = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append(C5292SGa.a());
        sb5.append(".action.ACTIVITY");
        e = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append(C5292SGa.a());
        sb6.append(".action.DISCOVERY");
        f = sb6.toString();
        StringBuilder sb7 = new StringBuilder();
        sb7.append(C5292SGa.a());
        sb7.append(".action.SEARCH");
        g = sb7.toString();
        StringBuilder sb8 = new StringBuilder();
        sb8.append(C5292SGa.a());
        sb8.append(".action.PERFORM_SEARCH");
        h = sb8.toString();
        StringBuilder sb9 = new StringBuilder();
        sb9.append(C5292SGa.a());
        sb9.append(".SHARE");
        i = sb9.toString();
        StringBuilder sb10 = new StringBuilder();
        sb10.append(C5292SGa.a());
        sb10.append(".EDIT");
        j = sb10.toString();
        StringBuilder sb11 = new StringBuilder();
        sb11.append(C5292SGa.a());
        sb11.append(".action.TRACK");
        k = sb11.toString();
        StringBuilder sb12 = new StringBuilder();
        sb12.append(C5292SGa.a());
        sb12.append(".action.COLLECTION");
        l = sb12.toString();
        StringBuilder sb13 = new StringBuilder();
        sb13.append(C5292SGa.a());
        sb13.append(".action.MORE");
        m = sb13.toString();
        StringBuilder sb14 = new StringBuilder();
        sb14.append(C5292SGa.a());
        sb14.append(".extra.title");
        n = sb14.toString();
        StringBuilder sb15 = new StringBuilder();
        sb15.append(C5292SGa.a());
        sb15.append(".extra.description");
        o = sb15.toString();
        StringBuilder sb16 = new StringBuilder();
        sb16.append(C5292SGa.a());
        sb16.append(".extra.public");
        p = sb16.toString();
        StringBuilder sb17 = new StringBuilder();
        sb17.append(C5292SGa.a());
        sb17.append(".extra.tags");
        q = sb17.toString();
        StringBuilder sb18 = new StringBuilder();
        sb18.append(C5292SGa.a());
        sb18.append(".extra.genre");
        r = sb18.toString();
        StringBuilder sb19 = new StringBuilder();
        sb19.append(C5292SGa.a());
        sb19.append(".extra.artwork");
        s = sb19.toString();
        StringBuilder sb20 = new StringBuilder();
        sb20.append(C5292SGa.a());
        sb20.append(".action.SHORTCUT_PLAY_LIKES");
        t = sb20.toString();
        StringBuilder sb21 = new StringBuilder();
        sb21.append(C5292SGa.a());
        sb21.append(".action.SHORTCUT_SEARCH");
        u = sb21.toString();
        StringBuilder sb22 = new StringBuilder();
        sb22.append(C5292SGa.a());
        sb22.append(".actions.upload.monitor");
        v = sb22.toString();
    }
}
